name: TTCore
version: 1.0
main: TTCore.TTCoreMain
depend: [Vault]
commands:
  developer:
    usage: /developer
    description: All the developer commands for TTCore
  ttcore:
    usage: /ttcore
    description: ttcore host commands